### PR TITLE
Added nexa protocol

### PR DESCRIPTION
**Pull request by xnaveira**
Hi! I wanted to use NEXA devices with HomeAssistant and I saw that they are using this library.

These devices are very popular here in Sweden: https://www.nexa.se/
There is a very good description of the protocol here: http://tech.jolowe.se/home-automation-rf-protocols/

This PR contains the code for adding the protocol to the library and to be able to send messages to the devices.

At the moment I'm looking to the rx part to be able to sniff codes as well but I still haven't wrapped my head around the code and how to modify it so it works with the new protocol.

### CODE REVIEW

**Comment by milaq** [comment]
Thanks for your PR.

I'm quite busy atm, but I'll have a look at it ASAP.

**Comment by Str33** [comment]
Is there a problem merging this code? Or why is nothing happening? More and more devices at the market are using this protocol.

**Comment by escoand** [comment]
It seems like the library is missing an active maintainer. Is there any active fork or an alternative to this library at all known?

**Comment by milaq** [comment]
I've rebased and merged your change.
Thanks and sorry for taking so long :+1:

**Comment by xnaveira** [comment]
Thank you sir! :)

Xavier

**Pull request merged**
